#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Convert Squareline Studio CMakeLists.txt to ESP-IDF format
"""
import re
import os
import sys

def convert_cmake():
    ui_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Đọc từ file backup của Squareline
    squareline_cmake = os.path.join(ui_dir, 'CMakeLists.txt.squareline')
    output_cmake = os.path.join(ui_dir, 'CMakeLists.txt')
    
    if not os.path.exists(squareline_cmake):
        print(f"Error: {squareline_cmake} not found!")
        print("Please export from Squareline Studio first")
        return False
    
    with open(squareline_cmake, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Tìm SOURCES
    sources_match = re.search(r'SET\(SOURCES\s+(.*?)\)', content, re.DOTALL)
    if not sources_match:
        print("Error: Cannot find SOURCES")
        return False
    
    sources_raw = sources_match.group(1)
    sources = [line.strip() for line in sources_raw.split('\n') if line.strip()]
    
    # Format sources cho ESP-IDF
    srcs_formatted = '\n         '.join(f'"{src}"' for src in sources)
    
    cmake_content = f'''# Auto-generated from Squareline Studio
# Generated by setup_ui.py
# Do not edit manually

idf_component_register(
    SRCS {srcs_formatted}
    INCLUDE_DIRS "."
    REQUIRES lvgl esp_lvgl_port
)
'''
    
    with open(output_cmake, 'w', encoding='utf-8') as f:
        f.write(cmake_content)
    
    # Dùng [OK] thay vì ✓ cho Windows
    print(f"[OK] Converted {len(sources)} files to ESP-IDF CMakeLists.txt")
    return True

if __name__ == '__main__':
    # Set UTF-8 encoding cho console Windows
    if sys.platform == 'win32':
        try:
            sys.stdout.reconfigure(encoding='utf-8')
        except:
            pass
    
    sys.exit(0 if convert_cmake() else 1)