// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_scrSplash.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_scrSetting.h"
#include "screens/ui_Screen1.h"
#include "screens/ui_scrMain.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_scrsplash_background_png);    // assets/scrSplash_background.png
LV_IMG_DECLARE(ui_img_scrsplash_loadingbarface_png);    // assets/scrSplash_loadingBarFace.png
LV_IMG_DECLARE(ui_img_scrnotconnected_background_png);    // assets/scrNotConnected_background.png
LV_IMG_DECLARE(ui_img_scrnotconnected_warningicon_png);    // assets/scrNotConnected_warningIcon.png
LV_IMG_DECLARE(ui_img_scrnotconnected_close_png);    // assets/scrNotConnected_close.png
LV_IMG_DECLARE(ui_img_scrsetting_list_png);    // assets/scrSetting_list.png
LV_IMG_DECLARE(ui_img_scrmain_background_png);    // assets/scrMain_background.png
LV_IMG_DECLARE(ui_img_scrsettingicon_png);    // assets/scrSettingIcon.png
LV_IMG_DECLARE(ui_img_scrmain_batteryempty_png);    // assets/scrMain_batteryEmpty.png
LV_IMG_DECLARE(ui_img_scrmain_batterywarning_png);    // assets/scrMain_batteryWarning.png
LV_IMG_DECLARE(ui_img_scrmain_lineslot1torobot_png);    // assets/scrMain_lineSlot1ToRobot.png
LV_IMG_DECLARE(ui_img_scrmain_lineslot2torobot_png);    // assets/scrMain_lineSlot2ToRobot.png
LV_IMG_DECLARE(ui_img_scrmain_lineslot3torobot_png);    // assets/scrMain_lineSlot3ToRobot.png
LV_IMG_DECLARE(ui_img_scrmain_lineslot4torobot_png);    // assets/scrMain_lineSlot4ToRobot.png
LV_IMG_DECLARE(ui_img_scrmain_lineslot5torobot_png);    // assets/scrMain_lineSlot5ToRobot.png
LV_IMG_DECLARE(ui_img_scrmain_batteryicon_png);    // assets/scrMain_batteryIcon.png
LV_IMG_DECLARE(ui_img_scrmain_robotcharging_png);    // assets/scrMain_robotCharging.png
LV_IMG_DECLARE(ui_img_scrmain_robotlowbattery_png);    // assets/scrMain_robotLowBattery.png
LV_IMG_DECLARE(ui_img_scrmain_robotfullbattery_png);    // assets/scrMain_robotFullBattery.png
LV_IMG_DECLARE(ui_img_scrmain_linerobottoslot1_png);    // assets/scrMain_lineRobotToSlot1.png
LV_IMG_DECLARE(ui_img_scrmain_linerobottoslot2_png);    // assets/scrMain_lineRobotToSlot2.png
LV_IMG_DECLARE(ui_img_scrmain_linerobottoslot3_png);    // assets/scrMain_lineRobotToSlot3.png
LV_IMG_DECLARE(ui_img_scrmain_linerobottoslot4_png);    // assets/scrMain_lineRobotToSlot4.png
LV_IMG_DECLARE(ui_img_scrmain_linerobottoslot5_png);    // assets/scrMain_lineRobotToSlot5.png
LV_IMG_DECLARE(ui_img_scrnotconnecticon_png);    // assets/scrNotConnectIcon.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
