// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef _SQUARELINE_RBCS_HMI_UI_H
#define _SQUARELINE_RBCS_HMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_scrsplash_background_png);    // assets/scrSplash_background.png
LV_IMG_DECLARE(ui_img_robot_4_png);    // assets/robot 4.png
LV_IMG_DECLARE(ui_img_scrmain_batteryempty_png);    // assets/scrMain_batteryEmpty.png
LV_IMG_DECLARE(ui_img_scrsettingicon_png);    // assets/scrSettingIcon.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
