// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_BAR1_H
#define _UI_COMP_BAR1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Bar1
#define UI_COMP_BAR1_BAR1 0
#define _UI_COMP_BAR1_NUM 1
lv_obj_t * ui_Bar1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
