// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_imgMainBackground = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMainBackground = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_imgMainBackground, &ui_img_imgmainbackground_png);
    lv_obj_set_width(ui_imgMainBackground, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_imgMainBackground, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_imgMainBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_imgMainBackground = NULL;

}
