// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRSPLASH_H
#define UI_SCRSPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSplash
extern void ui_scrSplash_screen_init(void);
extern void ui_scrSplash_screen_destroy(void);
extern lv_obj_t * ui_scrSplash;
extern lv_obj_t * ui_scrSplashBackground;
extern lv_obj_t * ui_scrSplashRobotLoading;
extern lv_obj_t * ui_scrSplashBarLoading;
extern lv_obj_t * ui_scrSplashNotiText;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrSplash;
extern lv_obj_t * uic_scrSplashBackground;
extern lv_obj_t * uic_scrSplashRobotLoading;
extern lv_obj_t * uic_scrSplashBarLoading;
extern lv_obj_t * uic_scrSplashNotiText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

