// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_scrNCNoti;
lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_scrNCNoti = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image11, &ui_img_scrnotconnected_background_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 637
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 425
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrNCNoti = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_scrNCNoti, &ui_img_scrnotconnected_warningicon_png);
    lv_obj_set_width(ui_scrNCNoti, LV_SIZE_CONTENT);   /// 202
    lv_obj_set_height(ui_scrNCNoti, LV_SIZE_CONTENT);    /// 202
    lv_obj_set_x(ui_scrNCNoti, 7);
    lv_obj_set_y(ui_scrNCNoti, -69);
    lv_obj_set_align(ui_scrNCNoti, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrNCNoti, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrNCNoti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image13, &ui_img_scrnotconnected_close_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image13, 12);
    lv_obj_set_y(ui_Image13, 157);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 5);
    lv_obj_set_y(ui_Label2, 71);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "NOT CONNECTED TO MAINBOARD  ");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xEF0B32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_scrNCNoti = ui_scrNCNoti;

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image11 = NULL;
    uic_scrNCNoti = NULL;
    ui_scrNCNoti = NULL;
    ui_Image13 = NULL;
    ui_Label2 = NULL;

}
