// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_scrMainBackground;
extern lv_obj_t * ui_scrMainTextDeviceName;
extern lv_obj_t * ui_scrMainTextSlot1;
extern lv_obj_t * ui_scrMainTextSlot2;
extern lv_obj_t * ui_scrMainTextSlot3;
extern lv_obj_t * ui_scrMainTextSlot4;
extern lv_obj_t * ui_scrMainTextSlot5;
extern lv_obj_t * ui_scrMainSettingIcon;
extern lv_obj_t * ui_scrMainEBatteryIcon1;
extern lv_obj_t * ui_scrMainEBatteryIcon2;
extern lv_obj_t * ui_scrMainEBatteryIcon3;
extern lv_obj_t * ui_scrMainEBatteryIcon4;
extern lv_obj_t * ui_scrMainEBatteryIcon5;
extern lv_obj_t * ui_scrMainBatCap1;
extern lv_obj_t * ui_scrMainBatCap2;
extern lv_obj_t * ui_scrMainBatCap3;
extern lv_obj_t * ui_scrMainBatCap4;
extern lv_obj_t * ui_scrMainBatCap5;
extern lv_obj_t * ui_scrMainBatWarning1;
extern lv_obj_t * ui_scrMainBatWarning2;
extern lv_obj_t * ui_scrMainBatWarning3;
extern lv_obj_t * ui_scrMainBatWarning4;
extern lv_obj_t * ui_scrMainBatWarning5;
extern lv_obj_t * ui_scrMainLineSlotToRobot1;
extern lv_obj_t * ui_scrMainLineSlotToRobot2;
extern lv_obj_t * ui_scrMainLineSlotToRobot3;
extern lv_obj_t * ui_scrMainLineSlotToRobot4;
extern lv_obj_t * ui_scrMainLineSlotToRobot5;
extern lv_obj_t * ui_scrMainBatteryRunIcon;
extern lv_obj_t * ui_scrMainRobotCharging;
extern lv_obj_t * ui_scrMainRobotEmpty;
extern lv_obj_t * ui_scrMainRobotFull;
extern lv_obj_t * ui_scrMainLineRobotToSlot1;
extern lv_obj_t * ui_scrMainLineRobotToSlot2;
extern lv_obj_t * ui_scrMainLineRobotToSlot3;
extern lv_obj_t * ui_scrMainLineRobotToSlot4;
extern lv_obj_t * ui_scrMainLineRobotToSlot5;
extern lv_obj_t * ui_scrMainNotifyBackground;
extern lv_obj_t * ui_scrMainNotConnected;
extern lv_obj_t * ui_scrMainCloseButton;
extern lv_obj_t * ui_scrMainNotConnectedImg;
extern lv_obj_t * ui_scrMainTextBAtNCNotifi;
extern lv_obj_t * ui_scrMainTextSlotNamInf;
extern lv_obj_t * ui_scrMainTextSlotInformation;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrMain;
extern lv_obj_t * uic_scrMainTextSlot1;
extern lv_obj_t * uic_scrMainTextSlot2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

