// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton6 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_scrsettingicon_png, NULL);
    lv_obj_set_width(ui_ImgButton6, 50);
    lv_obj_set_height(ui_ImgButton6, 50);
    lv_obj_set_x(ui_ImgButton6, 372);
    lv_obj_set_y(ui_ImgButton6, -213);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_Image15 = lv_img_create(ui_Screen3);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 780
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_x(ui_Image15, 0);
    lv_obj_set_y(ui_Image15, 30);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 18);
    lv_obj_set_y(ui_Label6, -216);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "BATTERY SLOT DETAILS");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -377);
    lv_obj_set_y(ui_Label7, -143);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "1");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_ImgButton6 = NULL;
    ui_Image15 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;

}
