// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_scrMainTextSlot2;
lv_obj_t * uic_scrMainTextSlot1;
lv_obj_t * uic_scrMain;
lv_obj_t * ui_scrMain = NULL;
lv_obj_t * ui_scrMainBackground = NULL;
lv_obj_t * ui_scrMainTextDeviceName = NULL;
lv_obj_t * ui_scrMainTextSlot1 = NULL;
lv_obj_t * ui_scrMainTextSlot2 = NULL;
lv_obj_t * ui_scrMainTextSlot3 = NULL;
lv_obj_t * ui_scrMainTextSlot4 = NULL;
lv_obj_t * ui_scrMainTextSlot5 = NULL;
lv_obj_t * ui_scrMainSettingIcon = NULL;
lv_obj_t * ui_scrMainEBatteryIcon1 = NULL;
lv_obj_t * ui_scrMainEBatteryIcon2 = NULL;
lv_obj_t * ui_scrMainEBatteryIcon3 = NULL;
lv_obj_t * ui_scrMainEBatteryIcon4 = NULL;
lv_obj_t * ui_scrMainEBatteryIcon5 = NULL;
lv_obj_t * ui_scrMainBatCap1 = NULL;
lv_obj_t * ui_scrMainBatCap2 = NULL;
lv_obj_t * ui_scrMainBatCap3 = NULL;
lv_obj_t * ui_scrMainBatCap4 = NULL;
lv_obj_t * ui_scrMainBatCap5 = NULL;
lv_obj_t * ui_scrMainBatWarning1 = NULL;
lv_obj_t * ui_scrMainBatWarning2 = NULL;
lv_obj_t * ui_scrMainBatWarning3 = NULL;
lv_obj_t * ui_scrMainBatWarning4 = NULL;
lv_obj_t * ui_scrMainBatWarning5 = NULL;
lv_obj_t * ui_scrMainLineSlotToRobot1 = NULL;
lv_obj_t * ui_scrMainLineSlotToRobot2 = NULL;
lv_obj_t * ui_scrMainLineSlotToRobot3 = NULL;
lv_obj_t * ui_scrMainLineSlotToRobot4 = NULL;
lv_obj_t * ui_scrMainLineSlotToRobot5 = NULL;
lv_obj_t * ui_scrMainBatteryRunIcon = NULL;
lv_obj_t * ui_scrMainRobotCharging = NULL;
lv_obj_t * ui_scrMainRobotEmpty = NULL;
lv_obj_t * ui_scrMainRobotFull = NULL;
lv_obj_t * ui_scrMainLineRobotToSlot1 = NULL;
lv_obj_t * ui_scrMainLineRobotToSlot2 = NULL;
lv_obj_t * ui_scrMainLineRobotToSlot3 = NULL;
lv_obj_t * ui_scrMainLineRobotToSlot4 = NULL;
lv_obj_t * ui_scrMainLineRobotToSlot5 = NULL;
lv_obj_t * ui_scrMainNotifyBackground = NULL;
lv_obj_t * ui_scrMainNotConnected = NULL;
lv_obj_t * ui_scrMainCloseButton = NULL;
lv_obj_t * ui_scrMainNotConnectedImg = NULL;
lv_obj_t * ui_scrMainTextBAtNCNotifi = NULL;
lv_obj_t * ui_scrMainTextSlotNamInf = NULL;
lv_obj_t * ui_scrMainTextSlotInformation = NULL;
// event funtions

// build funtions

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainBackground = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainBackground, &ui_img_scrmain_background_png);
    lv_obj_set_width(ui_scrMainBackground, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_scrMainBackground, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_scrMainBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainTextDeviceName = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextDeviceName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextDeviceName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextDeviceName, 135);
    lv_obj_set_y(ui_scrMainTextDeviceName, -218);
    lv_obj_set_align(ui_scrMainTextDeviceName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextDeviceName, "BATTERY STATION");
    lv_label_set_recolor(ui_scrMainTextDeviceName, "true");
    lv_obj_set_style_text_font(ui_scrMainTextDeviceName, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrMainTextSlot1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextSlot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextSlot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextSlot1, -363);
    lv_obj_set_y(ui_scrMainTextSlot1, -220);
    lv_obj_set_align(ui_scrMainTextSlot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextSlot1, "SLOT1");
    lv_obj_set_style_text_font(ui_scrMainTextSlot1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrMainTextSlot2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextSlot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextSlot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextSlot2, -363);
    lv_obj_set_y(ui_scrMainTextSlot2, -124);
    lv_obj_set_align(ui_scrMainTextSlot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextSlot2, "SLOT2");
    lv_obj_set_style_text_font(ui_scrMainTextSlot2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrMainTextSlot3 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextSlot3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextSlot3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextSlot3, -363);
    lv_obj_set_y(ui_scrMainTextSlot3, -28);
    lv_obj_set_align(ui_scrMainTextSlot3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextSlot3, "SLOT3");
    lv_obj_set_style_text_font(ui_scrMainTextSlot3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrMainTextSlot4 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextSlot4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextSlot4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextSlot4, -363);
    lv_obj_set_y(ui_scrMainTextSlot4, 66);
    lv_obj_set_align(ui_scrMainTextSlot4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextSlot4, "SLOT4");
    lv_obj_set_style_text_font(ui_scrMainTextSlot4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrMainTextSlot5 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextSlot5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextSlot5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextSlot5, -362);
    lv_obj_set_y(ui_scrMainTextSlot5, 164);
    lv_obj_set_align(ui_scrMainTextSlot5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextSlot5, "SLOT5");
    lv_obj_set_style_text_font(ui_scrMainTextSlot5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrMainSettingIcon = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainSettingIcon, &ui_img_scrsettingicon_png);
    lv_obj_set_width(ui_scrMainSettingIcon, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_scrMainSettingIcon, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_scrMainSettingIcon, 369);
    lv_obj_set_y(ui_scrMainSettingIcon, -209);
    lv_obj_set_align(ui_scrMainSettingIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainSettingIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainSettingIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainEBatteryIcon1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainEBatteryIcon1, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_scrMainEBatteryIcon1, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_scrMainEBatteryIcon1, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_scrMainEBatteryIcon1, -366);
    lv_obj_set_y(ui_scrMainEBatteryIcon1, -185);
    lv_obj_set_align(ui_scrMainEBatteryIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainEBatteryIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainEBatteryIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainEBatteryIcon2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainEBatteryIcon2, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_scrMainEBatteryIcon2, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_scrMainEBatteryIcon2, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_scrMainEBatteryIcon2, -366);
    lv_obj_set_y(ui_scrMainEBatteryIcon2, -89);
    lv_obj_set_align(ui_scrMainEBatteryIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainEBatteryIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainEBatteryIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainEBatteryIcon3 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainEBatteryIcon3, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_scrMainEBatteryIcon3, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_scrMainEBatteryIcon3, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_scrMainEBatteryIcon3, -366);
    lv_obj_set_y(ui_scrMainEBatteryIcon3, 7);
    lv_obj_set_align(ui_scrMainEBatteryIcon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainEBatteryIcon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainEBatteryIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainEBatteryIcon4 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainEBatteryIcon4, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_scrMainEBatteryIcon4, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_scrMainEBatteryIcon4, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_scrMainEBatteryIcon4, -366);
    lv_obj_set_y(ui_scrMainEBatteryIcon4, 101);
    lv_obj_set_align(ui_scrMainEBatteryIcon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainEBatteryIcon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainEBatteryIcon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainEBatteryIcon5 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainEBatteryIcon5, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_scrMainEBatteryIcon5, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_scrMainEBatteryIcon5, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_scrMainEBatteryIcon5, -366);
    lv_obj_set_y(ui_scrMainEBatteryIcon5, 199);
    lv_obj_set_align(ui_scrMainEBatteryIcon5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainEBatteryIcon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainEBatteryIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainBatCap1 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_scrMainBatCap1, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_scrMainBatCap1, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_scrMainBatCap1, 47);
    lv_obj_set_height(ui_scrMainBatCap1, 23);
    lv_obj_set_x(ui_scrMainBatCap1, 9);
    lv_obj_set_y(ui_scrMainBatCap1, 44);
    lv_obj_set_style_bg_color(ui_scrMainBatCap1, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scrMainBatCap1, lv_color_hex(0x232323), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_scrMainBatCap2 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_scrMainBatCap2, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_scrMainBatCap2, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_scrMainBatCap2, 47);
    lv_obj_set_height(ui_scrMainBatCap2, 23);
    lv_obj_set_x(ui_scrMainBatCap2, 9);
    lv_obj_set_y(ui_scrMainBatCap2, 140);
    lv_obj_add_flag(ui_scrMainBatCap2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_scrMainBatCap2, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scrMainBatCap2, lv_color_hex(0x232323), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_scrMainBatCap3 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_scrMainBatCap3, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_scrMainBatCap3, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_scrMainBatCap3, 47);
    lv_obj_set_height(ui_scrMainBatCap3, 23);
    lv_obj_set_x(ui_scrMainBatCap3, 9);
    lv_obj_set_y(ui_scrMainBatCap3, 236);
    lv_obj_add_flag(ui_scrMainBatCap3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_scrMainBatCap3, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scrMainBatCap3, lv_color_hex(0x232323), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_scrMainBatCap4 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_scrMainBatCap4, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_scrMainBatCap4, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_scrMainBatCap4, 47);
    lv_obj_set_height(ui_scrMainBatCap4, 23);
    lv_obj_set_x(ui_scrMainBatCap4, 9);
    lv_obj_set_y(ui_scrMainBatCap4, 330);
    lv_obj_add_flag(ui_scrMainBatCap4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_scrMainBatCap4, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scrMainBatCap4, lv_color_hex(0x232323), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_scrMainBatCap5 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_scrMainBatCap5, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_scrMainBatCap5, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_scrMainBatCap5, 47);
    lv_obj_set_height(ui_scrMainBatCap5, 23);
    lv_obj_set_x(ui_scrMainBatCap5, 9);
    lv_obj_set_y(ui_scrMainBatCap5, 428);
    lv_obj_add_flag(ui_scrMainBatCap5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_scrMainBatCap5, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scrMainBatCap5, lv_color_hex(0x232323), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMainBatCap5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_scrMainBatWarning1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainBatWarning1, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_scrMainBatWarning1, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_scrMainBatWarning1, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_scrMainBatWarning1, -368);
    lv_obj_set_y(ui_scrMainBatWarning1, -185);
    lv_obj_set_align(ui_scrMainBatWarning1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainBatWarning1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainBatWarning1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainBatWarning2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainBatWarning2, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_scrMainBatWarning2, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_scrMainBatWarning2, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_scrMainBatWarning2, -368);
    lv_obj_set_y(ui_scrMainBatWarning2, -89);
    lv_obj_set_align(ui_scrMainBatWarning2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainBatWarning2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainBatWarning2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainBatWarning3 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainBatWarning3, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_scrMainBatWarning3, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_scrMainBatWarning3, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_scrMainBatWarning3, -368);
    lv_obj_set_y(ui_scrMainBatWarning3, 7);
    lv_obj_set_align(ui_scrMainBatWarning3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainBatWarning3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainBatWarning3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainBatWarning4 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainBatWarning4, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_scrMainBatWarning4, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_scrMainBatWarning4, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_scrMainBatWarning4, -368);
    lv_obj_set_y(ui_scrMainBatWarning4, 101);
    lv_obj_set_align(ui_scrMainBatWarning4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainBatWarning4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainBatWarning4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainBatWarning5 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainBatWarning5, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_scrMainBatWarning5, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_scrMainBatWarning5, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_scrMainBatWarning5, -368);
    lv_obj_set_y(ui_scrMainBatWarning5, 199);
    lv_obj_set_align(ui_scrMainBatWarning5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainBatWarning5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainBatWarning5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineSlotToRobot1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineSlotToRobot1, &ui_img_scrmain_lineslot1torobot_png);
    lv_obj_set_width(ui_scrMainLineSlotToRobot1, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineSlotToRobot1, LV_SIZE_CONTENT);    /// 412
    lv_obj_set_x(ui_scrMainLineSlotToRobot1, 11);
    lv_obj_set_y(ui_scrMainLineSlotToRobot1, 3);
    lv_obj_set_align(ui_scrMainLineSlotToRobot1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineSlotToRobot1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineSlotToRobot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineSlotToRobot2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineSlotToRobot2, &ui_img_scrmain_lineslot2torobot_png);
    lv_obj_set_width(ui_scrMainLineSlotToRobot2, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineSlotToRobot2, LV_SIZE_CONTENT);    /// 316
    lv_obj_set_x(ui_scrMainLineSlotToRobot2, 11);
    lv_obj_set_y(ui_scrMainLineSlotToRobot2, 51);
    lv_obj_set_align(ui_scrMainLineSlotToRobot2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineSlotToRobot2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineSlotToRobot2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineSlotToRobot3 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineSlotToRobot3, &ui_img_scrmain_lineslot3torobot_png);
    lv_obj_set_width(ui_scrMainLineSlotToRobot3, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineSlotToRobot3, LV_SIZE_CONTENT);    /// 223
    lv_obj_set_x(ui_scrMainLineSlotToRobot3, 11);
    lv_obj_set_y(ui_scrMainLineSlotToRobot3, 97);
    lv_obj_set_align(ui_scrMainLineSlotToRobot3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineSlotToRobot3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineSlotToRobot3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineSlotToRobot4 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineSlotToRobot4, &ui_img_scrmain_lineslot4torobot_png);
    lv_obj_set_width(ui_scrMainLineSlotToRobot4, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineSlotToRobot4, LV_SIZE_CONTENT);    /// 130
    lv_obj_set_x(ui_scrMainLineSlotToRobot4, 11);
    lv_obj_set_y(ui_scrMainLineSlotToRobot4, 144);
    lv_obj_set_align(ui_scrMainLineSlotToRobot4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineSlotToRobot4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineSlotToRobot4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineSlotToRobot5 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineSlotToRobot5, &ui_img_scrmain_lineslot5torobot_png);
    lv_obj_set_width(ui_scrMainLineSlotToRobot5, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineSlotToRobot5, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_scrMainLineSlotToRobot5, 11);
    lv_obj_set_y(ui_scrMainLineSlotToRobot5, 194);
    lv_obj_set_align(ui_scrMainLineSlotToRobot5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineSlotToRobot5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineSlotToRobot5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainBatteryRunIcon = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainBatteryRunIcon, &ui_img_scrmain_batteryicon_png);
    lv_obj_set_width(ui_scrMainBatteryRunIcon, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_scrMainBatteryRunIcon, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_scrMainBatteryRunIcon, -64);
    lv_obj_set_y(ui_scrMainBatteryRunIcon, -182);
    lv_obj_set_align(ui_scrMainBatteryRunIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainBatteryRunIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainBatteryRunIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainRobotCharging = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainRobotCharging, &ui_img_scrmain_robotcharging_png);
    lv_obj_set_width(ui_scrMainRobotCharging, LV_SIZE_CONTENT);   /// 190
    lv_obj_set_height(ui_scrMainRobotCharging, LV_SIZE_CONTENT);    /// 190
    lv_obj_set_x(ui_scrMainRobotCharging, 275);
    lv_obj_set_y(ui_scrMainRobotCharging, 143);
    lv_obj_set_align(ui_scrMainRobotCharging, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainRobotCharging, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainRobotCharging, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainRobotEmpty = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainRobotEmpty, &ui_img_scrmain_robotlowbattery_png);
    lv_obj_set_width(ui_scrMainRobotEmpty, LV_SIZE_CONTENT);   /// 162
    lv_obj_set_height(ui_scrMainRobotEmpty, LV_SIZE_CONTENT);    /// 162
    lv_obj_set_x(ui_scrMainRobotEmpty, 260);
    lv_obj_set_y(ui_scrMainRobotEmpty, 155);
    lv_obj_set_align(ui_scrMainRobotEmpty, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainRobotEmpty, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainRobotEmpty, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainRobotFull = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainRobotFull, &ui_img_scrmain_robotfullbattery_png);
    lv_obj_set_width(ui_scrMainRobotFull, LV_SIZE_CONTENT);   /// 163
    lv_obj_set_height(ui_scrMainRobotFull, LV_SIZE_CONTENT);    /// 163
    lv_obj_set_x(ui_scrMainRobotFull, 259);
    lv_obj_set_y(ui_scrMainRobotFull, 155);
    lv_obj_set_align(ui_scrMainRobotFull, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainRobotFull, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainRobotFull, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineRobotToSlot1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineRobotToSlot1, &ui_img_scrmain_linerobottoslot1_png);
    lv_obj_set_width(ui_scrMainLineRobotToSlot1, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineRobotToSlot1, LV_SIZE_CONTENT);    /// 412
    lv_obj_set_x(ui_scrMainLineRobotToSlot1, 10);
    lv_obj_set_y(ui_scrMainLineRobotToSlot1, 3);
    lv_obj_set_align(ui_scrMainLineRobotToSlot1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineRobotToSlot1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineRobotToSlot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineRobotToSlot2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineRobotToSlot2, &ui_img_scrmain_linerobottoslot2_png);
    lv_obj_set_width(ui_scrMainLineRobotToSlot2, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineRobotToSlot2, LV_SIZE_CONTENT);    /// 316
    lv_obj_set_x(ui_scrMainLineRobotToSlot2, 10);
    lv_obj_set_y(ui_scrMainLineRobotToSlot2, 51);
    lv_obj_set_align(ui_scrMainLineRobotToSlot2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineRobotToSlot2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineRobotToSlot2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineRobotToSlot3 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineRobotToSlot3, &ui_img_scrmain_linerobottoslot3_png);
    lv_obj_set_width(ui_scrMainLineRobotToSlot3, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineRobotToSlot3, LV_SIZE_CONTENT);    /// 223
    lv_obj_set_x(ui_scrMainLineRobotToSlot3, 10);
    lv_obj_set_y(ui_scrMainLineRobotToSlot3, 97);
    lv_obj_set_align(ui_scrMainLineRobotToSlot3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineRobotToSlot3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineRobotToSlot3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineRobotToSlot4 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineRobotToSlot4, &ui_img_scrmain_linerobottoslot4_png);
    lv_obj_set_width(ui_scrMainLineRobotToSlot4, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineRobotToSlot4, LV_SIZE_CONTENT);    /// 130
    lv_obj_set_x(ui_scrMainLineRobotToSlot4, 10);
    lv_obj_set_y(ui_scrMainLineRobotToSlot4, 144);
    lv_obj_set_align(ui_scrMainLineRobotToSlot4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineRobotToSlot4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineRobotToSlot4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainLineRobotToSlot5 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainLineRobotToSlot5, &ui_img_scrmain_linerobottoslot5_png);
    lv_obj_set_width(ui_scrMainLineRobotToSlot5, LV_SIZE_CONTENT);   /// 299
    lv_obj_set_height(ui_scrMainLineRobotToSlot5, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_scrMainLineRobotToSlot5, 11);
    lv_obj_set_y(ui_scrMainLineRobotToSlot5, 194);
    lv_obj_set_align(ui_scrMainLineRobotToSlot5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainLineRobotToSlot5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainLineRobotToSlot5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainNotifyBackground = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainNotifyBackground, &ui_img_scrnotconnected_background_png);
    lv_obj_set_width(ui_scrMainNotifyBackground, LV_SIZE_CONTENT);   /// 637
    lv_obj_set_height(ui_scrMainNotifyBackground, LV_SIZE_CONTENT);    /// 425
    lv_obj_set_x(ui_scrMainNotifyBackground, -1);
    lv_obj_set_y(ui_scrMainNotifyBackground, -1);
    lv_obj_set_align(ui_scrMainNotifyBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainNotifyBackground, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainNotifyBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainNotConnected = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainNotConnected, &ui_img_scrnotconnecticon_png);
    lv_obj_set_width(ui_scrMainNotConnected, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_scrMainNotConnected, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_scrMainNotConnected, 368);
    lv_obj_set_y(ui_scrMainNotConnected, -154);
    lv_obj_set_align(ui_scrMainNotConnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainNotConnected, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainNotConnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainCloseButton = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainCloseButton, &ui_img_scrnotconnected_close_png);
    lv_obj_set_width(ui_scrMainCloseButton, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_scrMainCloseButton, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_scrMainCloseButton, 254);
    lv_obj_set_y(ui_scrMainCloseButton, 160);
    lv_obj_set_align(ui_scrMainCloseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainCloseButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainCloseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainNotConnectedImg = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_scrMainNotConnectedImg, &ui_img_scrnotconnected_warningicon_png);
    lv_obj_set_width(ui_scrMainNotConnectedImg, LV_SIZE_CONTENT);   /// 202
    lv_obj_set_height(ui_scrMainNotConnectedImg, LV_SIZE_CONTENT);    /// 202
    lv_obj_set_x(ui_scrMainNotConnectedImg, -5);
    lv_obj_set_y(ui_scrMainNotConnectedImg, -70);
    lv_obj_set_align(ui_scrMainNotConnectedImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrMainNotConnectedImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrMainNotConnectedImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrMainTextBAtNCNotifi = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextBAtNCNotifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextBAtNCNotifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextBAtNCNotifi, -2);
    lv_obj_set_y(ui_scrMainTextBAtNCNotifi, 74);
    lv_obj_set_align(ui_scrMainTextBAtNCNotifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextBAtNCNotifi, "NOT CONNECTED TO BOARD");
    lv_obj_add_flag(ui_scrMainTextBAtNCNotifi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_scrMainTextBAtNCNotifi, lv_color_hex(0xE10A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrMainTextBAtNCNotifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrMainTextBAtNCNotifi, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrMainTextSlotNamInf = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextSlotNamInf, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextSlotNamInf, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextSlotNamInf, -103);
    lv_obj_set_y(ui_scrMainTextSlotNamInf, -180);
    lv_obj_set_align(ui_scrMainTextSlotNamInf, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextSlotNamInf, "SLOT 1");
    lv_obj_add_flag(ui_scrMainTextSlotNamInf, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_scrMainTextSlotNamInf, lv_color_hex(0x354F80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrMainTextSlotNamInf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrMainTextSlotNamInf, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrMainTextSlotInformation = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_scrMainTextSlotInformation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrMainTextSlotInformation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrMainTextSlotInformation, 57);
    lv_obj_set_y(ui_scrMainTextSlotInformation, -180);
    lv_obj_set_align(ui_scrMainTextSlotInformation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrMainTextSlotInformation, "INFORMATION");
    lv_obj_add_flag(ui_scrMainTextSlotInformation, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_scrMainTextSlotInformation, lv_color_hex(0x354F80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrMainTextSlotInformation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrMainTextSlotInformation, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_scrMain = ui_scrMain;
    uic_scrMainTextSlot1 = ui_scrMainTextSlot1;
    uic_scrMainTextSlot2 = ui_scrMainTextSlot2;

}

void ui_scrMain_screen_destroy(void)
{
    if(ui_scrMain) lv_obj_del(ui_scrMain);

    // NULL screen variables
    uic_scrMain = NULL;
    ui_scrMain = NULL;
    ui_scrMainBackground = NULL;
    ui_scrMainTextDeviceName = NULL;
    uic_scrMainTextSlot1 = NULL;
    ui_scrMainTextSlot1 = NULL;
    uic_scrMainTextSlot2 = NULL;
    ui_scrMainTextSlot2 = NULL;
    ui_scrMainTextSlot3 = NULL;
    ui_scrMainTextSlot4 = NULL;
    ui_scrMainTextSlot5 = NULL;
    ui_scrMainSettingIcon = NULL;
    ui_scrMainEBatteryIcon1 = NULL;
    ui_scrMainEBatteryIcon2 = NULL;
    ui_scrMainEBatteryIcon3 = NULL;
    ui_scrMainEBatteryIcon4 = NULL;
    ui_scrMainEBatteryIcon5 = NULL;
    ui_scrMainBatCap1 = NULL;
    ui_scrMainBatCap2 = NULL;
    ui_scrMainBatCap3 = NULL;
    ui_scrMainBatCap4 = NULL;
    ui_scrMainBatCap5 = NULL;
    ui_scrMainBatWarning1 = NULL;
    ui_scrMainBatWarning2 = NULL;
    ui_scrMainBatWarning3 = NULL;
    ui_scrMainBatWarning4 = NULL;
    ui_scrMainBatWarning5 = NULL;
    ui_scrMainLineSlotToRobot1 = NULL;
    ui_scrMainLineSlotToRobot2 = NULL;
    ui_scrMainLineSlotToRobot3 = NULL;
    ui_scrMainLineSlotToRobot4 = NULL;
    ui_scrMainLineSlotToRobot5 = NULL;
    ui_scrMainBatteryRunIcon = NULL;
    ui_scrMainRobotCharging = NULL;
    ui_scrMainRobotEmpty = NULL;
    ui_scrMainRobotFull = NULL;
    ui_scrMainLineRobotToSlot1 = NULL;
    ui_scrMainLineRobotToSlot2 = NULL;
    ui_scrMainLineRobotToSlot3 = NULL;
    ui_scrMainLineRobotToSlot4 = NULL;
    ui_scrMainLineRobotToSlot5 = NULL;
    ui_scrMainNotifyBackground = NULL;
    ui_scrMainNotConnected = NULL;
    ui_scrMainCloseButton = NULL;
    ui_scrMainNotConnectedImg = NULL;
    ui_scrMainTextBAtNCNotifi = NULL;
    ui_scrMainTextSlotNamInf = NULL;
    ui_scrMainTextSlotInformation = NULL;

}
