// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_scrSetting;
lv_obj_t * ui_scrSetting = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image15 = NULL;
// event funtions

// build funtions

void ui_scrSetting_screen_init(void)
{
    ui_scrSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_scrSetting);
    lv_img_set_src(ui_Image14, &ui_img_scrsetting_list_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 764
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image14, -5);
    lv_obj_set_y(ui_Image14, -113);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_scrSetting);
    lv_img_set_src(ui_Image15, &ui_img_scrsetting_list_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 764
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image15, -3);
    lv_obj_set_y(ui_Image15, -54);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_scrSetting = ui_scrSetting;

}

void ui_scrSetting_screen_destroy(void)
{
    if(ui_scrSetting) lv_obj_del(ui_scrSetting);

    // NULL screen variables
    uic_scrSetting = NULL;
    ui_scrSetting = NULL;
    ui_Image14 = NULL;
    ui_Image15 = NULL;

}
