// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRSETTING_H
#define UI_SCRSETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSetting
extern void ui_scrSetting_screen_init(void);
extern void ui_scrSetting_screen_destroy(void);
extern lv_obj_t * ui_scrSetting;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrSetting;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

