// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_scrSplashNotiText;
lv_obj_t * uic_scrSplashBarLoading;
lv_obj_t * uic_scrSplashRobotLoading;
lv_obj_t * uic_scrSplashBackground;
lv_obj_t * uic_scrSplash;
lv_obj_t * ui_scrSplash = NULL;
lv_obj_t * ui_scrSplashBackground = NULL;
lv_obj_t * ui_scrSplashRobotLoading = NULL;
lv_obj_t * ui_scrSplashBarLoading = NULL;
lv_obj_t * ui_scrSplashNotiText = NULL;
// event funtions

// build funtions

void ui_scrSplash_screen_init(void)
{
    ui_scrSplash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrSplash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrSplashBackground = lv_img_create(ui_scrSplash);
    lv_img_set_src(ui_scrSplashBackground, &ui_img_scrsplash_background_png);
    lv_obj_set_width(ui_scrSplashBackground, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_scrSplashBackground, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_scrSplashBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrSplashBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrSplashBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrSplashRobotLoading = lv_img_create(ui_scrSplash);
    lv_img_set_src(ui_scrSplashRobotLoading, &ui_img_scrsplash_loadingbarface_png);
    lv_obj_set_width(ui_scrSplashRobotLoading, LV_SIZE_CONTENT);   /// 72
    lv_obj_set_height(ui_scrSplashRobotLoading, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_scrSplashRobotLoading, -201);
    lv_obj_set_y(ui_scrSplashRobotLoading, 185);
    lv_obj_set_align(ui_scrSplashRobotLoading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrSplashRobotLoading, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrSplashRobotLoading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrSplashBarLoading = lv_bar_create(ui_scrSplash);
    lv_bar_set_value(ui_scrSplashBarLoading, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_scrSplashBarLoading, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_scrSplashBarLoading, 796);
    lv_obj_set_height(ui_scrSplashBarLoading, 10);
    lv_obj_set_x(ui_scrSplashBarLoading, 1);
    lv_obj_set_y(ui_scrSplashBarLoading, 467);
    lv_obj_set_style_bg_color(ui_scrSplashBarLoading, lv_color_hex(0xC7C4C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrSplashBarLoading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scrSplashBarLoading, lv_color_hex(0x354F80), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrSplashBarLoading, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_scrSplashNotiText = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_scrSplashNotiText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrSplashNotiText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrSplashNotiText, 12);
    lv_obj_set_y(ui_scrSplashNotiText, 14);
    lv_obj_set_align(ui_scrSplashNotiText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrSplashNotiText, "Initialize interface. . . ");

    uic_scrSplash = ui_scrSplash;
    uic_scrSplashBackground = ui_scrSplashBackground;
    uic_scrSplashRobotLoading = ui_scrSplashRobotLoading;
    uic_scrSplashBarLoading = ui_scrSplashBarLoading;
    uic_scrSplashNotiText = ui_scrSplashNotiText;

}

void ui_scrSplash_screen_destroy(void)
{
    if(ui_scrSplash) lv_obj_del(ui_scrSplash);

    // NULL screen variables
    uic_scrSplash = NULL;
    ui_scrSplash = NULL;
    uic_scrSplashBackground = NULL;
    ui_scrSplashBackground = NULL;
    uic_scrSplashRobotLoading = NULL;
    ui_scrSplashRobotLoading = NULL;
    uic_scrSplashBarLoading = NULL;
    ui_scrSplashBarLoading = NULL;
    uic_scrSplashNotiText = NULL;
    ui_scrSplashNotiText = NULL;

}
